import { dir } from 'i18next'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Header from '@/components/Header';
const roboto = Roboto({
    weight: ['400', '700', '300', '500'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({ children, params: {
    lng
} }: {
    children: React.ReactNode, params: {
        lng: string
    }
}) {
    return (
        <html lang={lng} dir={dir(lng)}>
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <body className={`${roboto.className} h-screen`}>
                <Header lng={lng} />
                {children}
            </body>
        </html>
    )
}